# Generated by Django 4.2.30 on 2026-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_delete_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
