# Generated by Django 4.2.30 on 2026-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
